/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_biu_SCProtocols_NativeSemiHonestYao_YaoParty */

#ifndef _Included_edu_biu_SCProtocols_NativeSemiHonestYao_YaoParty
#define _Included_edu_biu_SCProtocols_NativeSemiHonestYao_YaoParty
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     edu_biu_SCProtocols_NativeSemiHonestYao_YaoParty
	* Method:    createYaoParty
	* Signature: (ILjava/lang/String;)J
	*/
	JNIEXPORT jlong JNICALL Java_edu_biu_SCProtocols_NativeSemiHonestYao_YaoParty_createYaoParty
		(JNIEnv *, jobject, jint, jstring);

	/*
	* Class:     edu_biu_SCProtocols_NativeSemiHonestYao_YaoParty
	* Method:    runProtocol
	* Signature: (IIJ)[B
	*/
	JNIEXPORT jbyteArray JNICALL Java_edu_biu_SCProtocols_NativeSemiHonestYao_YaoParty_runProtocol
		(JNIEnv *, jobject, jint, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif