/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "Util.h"
#include <stdio.h>
#include <string.h>
#include <openssl/sha.h>

/* Header for class edu_biu_protocols_yao_primitives_KProbeResistantMatrix */

#ifndef _Included_edu_biu_protocols_yao_
#define _Included_edu_biu_protocols_yao_
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_biu_protocols_yao_primitives_KProbeResistantMatrix
 * Method:    restoreKeys
 * Signature: ([B)[B
 */                         
JNIEXPORT void JNICALL Java_edu_biu_protocols_yao_primitives_KProbeResistantMatrix_restoreKeys
  (JNIEnv *, jobject, jbyteArray, jobjectArray, int, int, jbyteArray);

JNIEXPORT void JNICALL Java_edu_biu_protocols_yao_primitives_KProbeResistantMatrix_transformKeys
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, int n, int m, jobjectArray);


JNIEXPORT void JNICALL Java_edu_biu_protocols_yao_primitives_KProbeResistantMatrix_allocateKeys
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, int i, jbyteArray, int n, int m, jobjectArray);

/*
 * Class:     edu_biu_protocols_yao_primitives_KProbeResistantMatrix
 * Method:    restoreKeys
 * Signature: ([B)[B
 */                         
JNIEXPORT void JNICALL Java_edu_biu_protocols_yao_offlineOnline_specs_OnlineProtocolP2_xorKeysWithMask
  (JNIEnv *, jobject, jbyteArray, jbyteArray, int);

JNIEXPORT void JNICALL Java_edu_biu_protocols_yao_offlineOnline_specs_OnlineProtocolP2_xorKeys
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, int);

JNIEXPORT bool JNICALL Java_edu_biu_protocols_yao_offlineOnline_specs_OnlineProtocolP2_verifyDecommitment
	(JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
