//
// Created by moriya on 31/01/17.
//

//#ifndef LIBSCAPIJAVAINTERFACE_GMWPROTOCOL_H
//#define LIBSCAPIJAVAINTERFACE_GMWPROTOCOL_H

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_biu_SCProtocols_gmw_GmwParty */

#ifndef _Included_edu_biu_SCProtocols_gmw_GmwParty
#define _Included_edu_biu_SCProtocols_gmw_GmwParty

#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     edu_biu_SCProtocols_gmw_GmwParty
	* Method:    createGMWParty
	* Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;I)J
	*/
	JNIEXPORT jlong JNICALL Java_edu_biu_SCProtocols_gmw_GmwParty_createGMWParty
		(JNIEnv *, jobject, jint, jstring, jstring, jstring, jint);

	/*
	* Class:     edu_biu_SCProtocols_gmw_GmwParty
	* Method:    runProtocol
	* Signature: (J)[B
	*/
	JNIEXPORT jbyteArray JNICALL Java_edu_biu_SCProtocols_gmw_GmwParty_runProtocol
		(JNIEnv *, jobject, jlong);

	/*
	* Class:     edu_biu_SCProtocols_gmw_GmwParty
	* Method:    deleteGMW
	* Signature: (J)V
	*/
	JNIEXPORT void JNICALL Java_edu_biu_SCProtocols_gmw_GmwParty_deleteGMW
		(JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif



//#endif //LIBSCAPIJAVAINTERFACE_GMWPROTOCOL_H
